name: Release new version

on:
  push:
    branches:
      - main

jobs:
  windows-linux:
    runs-on: windows-latest

    steps:
      - name: disable auto crlf
        run: git config --global core.autocrlf false
        
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4.0.2

      - name: Get current version
        id: get_version
        run: |
          echo "::set-output name=version::$(node -p "require('./package.json').version")"

      - name: Check if release needed
        id: check_release
        run: |
          try {
          $LATEST_VERSION = (Invoke-WebRequest -Uri "https://api.github.com/repos/${{ github.repository }}/releases/latest").Content | ConvertFrom-Json | Select-Object -ExpandProperty tag_name -First 1
          if ($LATEST_VERSION -ne "${{ steps.get_version.outputs.version }}") {
            echo "::set-output name=release_needed::true"
          } else {
            echo "::set-output name=release_needed::false"
          }
          }
          catch {
            echo "::set-output name=release_needed::true"
          }

      - name: Install dependencies and build releases
        if: steps.check_release.outputs.release_needed == 'true'
        run: |
          npm i
          npx eslint --fix
          npm run release

      - name: Upload Windows unpacked
        if: steps.check_release.outputs.release_needed == 'true'
        uses: actions/upload-artifact@v4.3.1
        with:
          name: win-unpacked
          path: releases/win32/x64/win-unpacked

      - name: Upload Linux unpacked
        if: steps.check_release.outputs.release_needed == 'true'
        uses: actions/upload-artifact@v4.3.1
        with:
          name: lin-unpacked
          path: releases/win32/x64/linux-unpacked

      - name: Upload Squirrel.exe
        if: steps.check_release.outputs.release_needed == 'true'
        uses: actions/upload-artifact@v4.3.1
        with:
          name: squirrel.exe
          path: releases/win32/x64/squirrel-windows/*.exe

  release:
    runs-on: ubuntu-latest
    needs: windows-linux
    permissions:
      contents: write
    steps:
      - name: Get current version
        id: get_version
        run: |
          echo "::set-output name=version::$(node -p "require('./package.json').version")"

      - name: Check if release needed
        id: check_release
        run: |
          try {
          $LATEST_VERSION = (Invoke-WebRequest -Uri "https://api.github.com/repos/${{ github.repository }}/releases/latest").Content | ConvertFrom-Json | Select-Object -ExpandProperty tag_name -First 1
          if ($LATEST_VERSION -ne "${{ steps.get_version.outputs.version }}") {
            echo "::set-output name=release_needed::true"
          } else {
            echo "::set-output name=release_needed::false"
          }
          }
          catch {
            echo "::set-output name=release_needed::true"
          }
          
      - name: Create release
        uses: softprops/action-gh-release@v2
        if: steps.check_release.outputs.release_needed == 'true'
        with: 
          generate_release_notes: true
          tag_name: ${{ steps.get_version.outputs.version }}
      
      - name: Complete
        if: steps.check_release.outputs.release_needed == 'true'
        run: echo "New release created"
